import React from 'react'
import type { Metadata } from 'next'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import './globals.css'

export const metadata: Metadata = {
	title: 'InnoStruct',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<link
					href='https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,100..1000&display=swap'
					rel='stylesheet'
				/>
				<link
					rel='stylesheet'
					href='https://unicons.iconscout.com/release/v4.0.8/css/line.css'
				></link>
			</head>
			<body className='overflow-y-auto overflow-x-hidden'>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
